### PR TITLE
Magento 1x Release Notes June 2019

### PR DESCRIPTION
**Pull request by jfrontain**
When merged, this PR will update the M1x release notes to the latest version, which is scheduled or release on June 25, 2019. It will update these files: 

https://devdocs.magento.com/guides/m1x/ce19-ee114/ee1.14_release-notes.html
https://devdocs.magento.com/guides/m1x/ce19-ee114/ce1.9_release-notes.html

whatsnew
Added release notes for [Magento Commerce 1.14.4.2](https://devdocs.magento.com/guides/m1x/ce19-ee114/ee1.14_release-notes.html) and [Magento Open Source 1.9.4.2](https://devdocs.magento.com/guides/m1x/ce19-ee114/ce1.9_release-notes.html).

### CODE REVIEW

**Comment by dshevtsov** [comment]
@jfrontain please add `whatsnew` to the PR description.

**Comment by piotrekkaminski** [comment]
approved

**Comment by dshevtsov** [comment]
@jfrontain please add under the `whatsnew` a summary of the changes that this PR adds to the documentation. This summary will be added as an entry to the [What's New on DevDocs](https://devdocs.magento.com/whats-new.html) as well as in its RSS thread.
See example in magento/devdocs#4773

**Comment by meker12** [comment]
So I wasn't sure if the M1X release notes are supposed to be merged into `master` or `develop`.  This PR is against `develop`, and it includes 187 changed files, which makes me think that the release notes branch was created off of the `master` instead of `develop`. 

- If the updates are intended to be merged to `master`, then the PR base branch needs be change from `develop` to `master`.
- If the updates are intended to be merged to `develop`, then this branch needs to be rebased onto the `develop`branch.

**Pull request merged**
